Update check_links.yml

diff --git a/.github/workflows/check_links.yml b/.github/workflows/check_links.yml
--- a/.github/workflows/check_links.yml
+++ b/.github/workflows/check_links.yml
@@ -14,4 +14,15 @@ jobs:
         uses: actions/checkout@v2
       - name: Check Links
         run: |
-          grep -r 'https://' ./docs | grep -oP 'https://.*' | sed 's| .*||;s|).*||;s|`.*||' | xargs -i curl -sLI {} -o /dev/null -w "%{http_code}\n"
+          export LINKS="$(grep -r 'https://' ./docs | grep -oP 'https://.*' | sed 's| .*||;s|).*||;s|`.*||')"
+          mapfile -t LINKS <<< "$LINKS"
+          for link in "${LINKS[@]}"; \
+            do; \
+            if [ "$(curl -sLI "$link" -o /dev/null -w "%{http_code}\n")" != 200 ]; then; \
+                echo "$link is invalid."; \
+                export INVALID=1; \
+            fi; \
+            done
+          if [ -n "$INVALID" ]; then; \
+            exit 1; \
+          fi
